hp = 100;
motion = -1;
vel = -1;
damageHitbox = -1;
lastSprite = -1;
dazedCounter = 100;
dazed = instance_create(0,0,StateTemplate);
dazed.main = Enemy_Dazed;
dazed.sprite = instance_create(0,0, Animation);
